spring:
  application:
    name: JobOffers
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/joboffers
      auto-index-creation: true

offers:
  http:
    client:
      config:
        uri: http://ec2-18-194-181-208.eu-central-1.compute.amazonaws.com
        port: 5057
        path: /offers
        connectionTimeout: 5000
        readTimeout: 5000
        fixedDelay: PT3H
  jwt:
    config:
      secret: ${JWT_SECRET}
      issuer: Job Offers Service
      expirationDays: 30
logging:
  level:
    org:
      springframework:
        security: DEBUG